language: objective-c
osx_image: xcode7.3

install: 
  - git clone https://github.com/Electrode-iOS/ELFoundation.git ../ELFoundation
  - git clone https://github.com/Electrode-iOS/ELLog.git ../ELLog
script:
   - xctool -project ELJSBridge.xcodeproj -scheme ELJSBridge -sdk iphonesimulator build test
